// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @param {string} filePath
 * @returns {$CancellablePromise<boolean>}
 */
export function CrushFile(filePath) {
    return $Call.ByID(2385541468, filePath);
}

/**
 * @returns {$CancellablePromise<number>}
 */
export function GetTotalSpaceSaved() {
    return $Call.ByID(37128268);
}

/**
 * @returns {$CancellablePromise<$models.JunkFile[]>}
 */
export function ScanJunkFiles() {
    return $Call.ByID(3077169815).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

// Private type creation functions
const $$createType0 = $models.JunkFile.createFrom;
const $$createType1 = $Create.Array($$createType0);
