// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class JunkFile {
    /**
     * Creates a new JunkFile instance.
     * @param {Partial<JunkFile>} [$$source = {}] - The source object to create the JunkFile.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("sizeMB" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sizeMB"] = 0;
        }
        if (!("category" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["category"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new JunkFile instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {JunkFile}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new JunkFile(/** @type {Partial<JunkFile>} */($$parsedSource));
    }
}
